# Generated by Django 4.0.6 on 2022-11-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=512, null=True, verbose_name='Type check')),
                ('order', models.JSONField(blank=True, null=True, verbose_name='Order information')),
                ('status', models.CharField(blank=True, choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=15, null=True, verbose_name='Status check')),
                ('pdf_file', models.FileField(upload_to='media/pdf', verbose_name='Check format PDF')),
                ('printer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer', to='api.printer')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
